import type { CatalogEntry } from "./manifest";

/**
 * Docs-only catalog rows for bg/tooltip demos.
 * The `/charts` sync skips these (global preview controls cover the same surface);
 * docs pages still need named embeds for every MDX `<ComponentPreview>`.
 */
export const DOCS_EXTRA_CATALOG: CatalogEntry[] = [
  {
    id: "ex-bg-dots-line-chart",
    name: "Bg Dots Line",
    exportName: "NQExampleBgDotsLineChart",
    adapterFile: "ex-ui-charts.tsx",
    family: "line",
    category: "example",
    component: "background",
  },
  {
    id: "ex-bg-graph-paper-line-chart",
    name: "Bg Graph Paper Line",
    exportName: "NQExampleBgGraphPaperLineChart",
    adapterFile: "ex-ui-charts.tsx",
    family: "line",
    category: "example",
    component: "background",
  },
  {
    id: "ex-bg-cross-hatch-line-chart",
    name: "Bg Cross Hatch Line",
    exportName: "NQExampleBgCrossHatchLineChart",
    adapterFile: "ex-ui-charts.tsx",
    family: "line",
    category: "example",
    component: "background",
  },
  {
    id: "ex-bg-diagonal-lines-line-chart",
    name: "Bg Diagonal Lines Line",
    exportName: "NQExampleBgDiagonalLinesLineChart",
    adapterFile: "ex-ui-charts.tsx",
    family: "line",
    category: "example",
    component: "background",
  },
  {
    id: "ex-bg-plus-line-chart",
    name: "Bg Plus Line",
    exportName: "NQExampleBgPlusLineChart",
    adapterFile: "ex-ui-charts.tsx",
    family: "line",
    category: "example",
    component: "background",
  },
  {
    id: "ex-bg-falling-triangles-line-chart",
    name: "Bg Falling Triangles Line",
    exportName: "NQExampleBgFallingTrianglesLineChart",
    adapterFile: "ex-ui-charts.tsx",
    family: "line",
    category: "example",
    component: "background",
  },
  {
    id: "ex-bg-4-pointed-star-line-chart",
    name: "Bg 4 Pointed Star Line",
    exportName: "NQExampleBg4PointedStarLineChart",
    adapterFile: "ex-ui-charts.tsx",
    family: "line",
    category: "example",
    component: "background",
  },
  {
    id: "ex-bg-tiny-checkers-line-chart",
    name: "Bg Tiny Checkers Line",
    exportName: "NQExampleBgTinyCheckersLineChart",
    adapterFile: "ex-ui-charts.tsx",
    family: "line",
    category: "example",
    component: "background",
  },
  {
    id: "ex-bg-overlapping-circles-line-chart",
    name: "Bg Overlapping Circles Line",
    exportName: "NQExampleBgOverlappingCirclesLineChart",
    adapterFile: "ex-ui-charts.tsx",
    family: "line",
    category: "example",
    component: "background",
  },
  {
    id: "ex-bg-wiggle-lines-line-chart",
    name: "Bg Wiggle Lines Line",
    exportName: "NQExampleBgWiggleLinesLineChart",
    adapterFile: "ex-ui-charts.tsx",
    family: "line",
    category: "example",
    component: "background",
  },
  {
    id: "ex-bg-bubbles-line-chart",
    name: "Bg Bubbles Line",
    exportName: "NQExampleBgBubblesLineChart",
    adapterFile: "ex-ui-charts.tsx",
    family: "line",
    category: "example",
    component: "background",
  },
  {
    id: "ex-bg-bubbles-sparkline-chart",
    name: "Bg Bubbles Sparkline",
    exportName: "NQExampleBgBubblesSparklineChart",
    adapterFile: "ex-doc-charts.tsx",
    family: "sparkline",
    category: "example",
    component: "sparkline-chart",
  },
  {
    id: "ex-tooltip-default-bar-chart",
    name: "Tooltip Default Bar",
    exportName: "NQExampleTooltipDefaultBarChart",
    adapterFile: "ex-ui-charts.tsx",
    family: "bar",
    category: "example",
    component: "tooltip",
  },
  {
    id: "ex-tooltip-frosted-glass-bar-chart",
    name: "Tooltip Frosted Glass Bar",
    exportName: "NQExampleTooltipFrostedGlassBarChart",
    adapterFile: "ex-ui-charts.tsx",
    family: "bar",
    category: "example",
    component: "tooltip",
  },
];
