/* AUTO-GENERATED by scripts/sync-nqchart-catalog.mjs — do not edit. */
export type CatalogCategory =
  | "example"
  | "variant"
  | "recipe"
  | "legend"
  | "loading"
  | "matrix"
  | "block"
  | "other";

export type CatalogEntry = {
  id: string;
  name: string;
  exportName: string;
  adapterFile: string;
  family: string;
  category: CatalogCategory;
  component: string;
};

export const CATALOG_SOURCE = "nqchart" as const;
export const CATALOG_COUNT = 95 as const;

export const NQCHART_CATALOG: CatalogEntry[] = [
  {
    "id": "ex-animated-dashed-stroke-area-chart",
    "name": "Animated Dashed Stroke Area",
    "exportName": "NQExampleAnimatedDashedStrokeAreaChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "area",
    "category": "example",
    "component": "area-chart"
  },
  {
    "id": "ex-area-chart",
    "name": "Area",
    "exportName": "NQExampleAreaChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "area",
    "category": "example",
    "component": "area-chart"
  },
  {
    "id": "ex-bar-chart",
    "name": "Bar",
    "exportName": "NQExampleBarChart",
    "adapterFile": "ex-bar-chart.tsx",
    "family": "bar",
    "category": "example",
    "component": "bar-chart"
  },
  {
    "id": "ex-boxplot-chart",
    "name": "Boxplot",
    "exportName": "NQExampleBoxplotChart",
    "adapterFile": "ex-boxplot-chart.tsx",
    "family": "composed",
    "category": "recipe",
    "component": "composed-chart"
  },
  {
    "id": "ex-bubble-chart",
    "name": "Bubble",
    "exportName": "NQExampleBubbleChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "scatter",
    "category": "example",
    "component": "scatter-chart"
  },
  {
    "id": "ex-bubble-sized-chart",
    "name": "Bubble Sized",
    "exportName": "NQExampleBubbleSizedChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "scatter",
    "category": "example",
    "component": "scatter-chart"
  },
  {
    "id": "ex-bullet-chart",
    "name": "Bullet",
    "exportName": "NQExampleBulletChart",
    "adapterFile": "ex-bullet-chart.tsx",
    "family": "bar",
    "category": "recipe",
    "component": "bar-chart"
  },
  {
    "id": "ex-bump-curve-type-area-chart",
    "name": "Bump Curve Type Area",
    "exportName": "NQExampleBumpCurveTypeAreaChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "area",
    "category": "example",
    "component": "area-chart"
  },
  {
    "id": "ex-calendar-workload-chart",
    "name": "Calendar Workload",
    "exportName": "NQExampleCalendarWorkloadChart",
    "adapterFile": "ex-calendar-workload-chart.tsx",
    "family": "calendar",
    "category": "matrix",
    "component": "calendar-chart"
  },
  {
    "id": "ex-chart-config-default-bar-chart",
    "name": "Chart Config Default Bar",
    "exportName": "NQExampleChartConfigDefaultBarChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "bar",
    "category": "example",
    "component": "bar-chart"
  },
  {
    "id": "ex-chart-config-icons-bar-chart",
    "name": "Chart Config Icons Bar",
    "exportName": "NQExampleChartConfigIconsBarChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "bar",
    "category": "example",
    "component": "bar-chart"
  },
  {
    "id": "ex-circle-grid-radar-chart",
    "name": "Circle Grid Radar",
    "exportName": "NQExampleCircleGridRadarChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "radar",
    "category": "example",
    "component": "radar-chart"
  },
  {
    "id": "ex-composed-chart",
    "name": "Composed",
    "exportName": "NQExampleComposedChart",
    "adapterFile": "ex-composed-chart.tsx",
    "family": "composed",
    "category": "example",
    "component": "composed-chart"
  },
  {
    "id": "ex-dashed-stroke-area-chart",
    "name": "Dashed Stroke Area",
    "exportName": "NQExampleDashedStrokeAreaChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "area",
    "category": "example",
    "component": "area-chart"
  },
  {
    "id": "ex-default-type-area-chart",
    "name": "Default Type Area",
    "exportName": "NQExampleDefaultTypeAreaChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "area",
    "category": "example",
    "component": "area-chart"
  },
  {
    "id": "ex-dotted-area-variant-area-chart",
    "name": "Dotted Area Variant Area",
    "exportName": "NQExampleDottedAreaVariantAreaChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "area",
    "category": "example",
    "component": "area-chart"
  },
  {
    "id": "ex-expanded-type-area-chart",
    "name": "Expanded Type Area",
    "exportName": "NQExampleExpandedTypeAreaChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "area",
    "category": "example",
    "component": "area-chart"
  },
  {
    "id": "ex-funnel-chart",
    "name": "Funnel",
    "exportName": "NQExampleFunnelChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "funnel",
    "category": "example",
    "component": "funnel-chart"
  },
  {
    "id": "ex-gauge-chart",
    "name": "Gauge",
    "exportName": "NQExampleGaugeChart",
    "adapterFile": "ex-gauge-chart.tsx",
    "family": "radial",
    "category": "recipe",
    "component": "radial-chart"
  },
  {
    "id": "ex-gauge-with-target-chart",
    "name": "Gauge With Target",
    "exportName": "NQExampleGaugeWithTargetChart",
    "adapterFile": "ex-gauge-with-target-chart.tsx",
    "family": "radial",
    "category": "recipe",
    "component": "radial-chart"
  },
  {
    "id": "ex-glowing-bubble-chart",
    "name": "Glowing Bubble",
    "exportName": "NQExampleGlowingBubbleChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "scatter",
    "category": "variant",
    "component": "scatter-chart"
  },
  {
    "id": "ex-glowing-funnel-chart",
    "name": "Glowing Funnel",
    "exportName": "NQExampleGlowingFunnelChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "funnel",
    "category": "variant",
    "component": "funnel-chart"
  },
  {
    "id": "ex-glowing-radar-chart",
    "name": "Glowing Radar",
    "exportName": "NQExampleGlowingRadarChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "radar",
    "category": "variant",
    "component": "radar-chart"
  },
  {
    "id": "ex-glowing-radial-chart",
    "name": "Glowing Radial",
    "exportName": "NQExampleGlowingRadialChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "radial",
    "category": "variant",
    "component": "radial-chart"
  },
  {
    "id": "ex-glowing-scatter-chart",
    "name": "Glowing Scatter",
    "exportName": "NQExampleGlowingScatterChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "scatter",
    "category": "variant",
    "component": "scatter-chart"
  },
  {
    "id": "ex-glowing-sparkline-chart",
    "name": "Glowing Sparkline",
    "exportName": "NQExampleGlowingSparklineChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "line",
    "category": "variant",
    "component": "sparkline-chart"
  },
  {
    "id": "ex-glowing-treemap-chart",
    "name": "Glowing Treemap",
    "exportName": "NQExampleGlowingTreemapChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "treemap",
    "category": "variant",
    "component": "treemap-chart"
  },
  {
    "id": "ex-glowing-waterfall-chart",
    "name": "Glowing Waterfall",
    "exportName": "NQExampleGlowingWaterfallChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "waterfall",
    "category": "variant",
    "component": "waterfall-chart"
  },
  {
    "id": "ex-gradient-area-variant-area-chart",
    "name": "Gradient Area Variant Area",
    "exportName": "NQExampleGradientAreaVariantAreaChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "area",
    "category": "variant",
    "component": "area-chart"
  },
  {
    "id": "ex-gradient-colors-area-chart",
    "name": "Gradient Colors Area",
    "exportName": "NQExampleGradientColorsAreaChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "area",
    "category": "variant",
    "component": "area-chart"
  },
  {
    "id": "ex-gradient-colors-bar-chart",
    "name": "Gradient Colors Bar",
    "exportName": "NQExampleGradientColorsBarChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "bar",
    "category": "variant",
    "component": "bar-chart"
  },
  {
    "id": "ex-gradient-colors-bump-area-chart",
    "name": "Gradient Colors Bump Area",
    "exportName": "NQExampleGradientColorsBumpAreaChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "area",
    "category": "variant",
    "component": "area-chart"
  },
  {
    "id": "ex-gradient-colors-radar-chart",
    "name": "Gradient Colors Radar",
    "exportName": "NQExampleGradientColorsRadarChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "radar",
    "category": "variant",
    "component": "radar-chart"
  },
  {
    "id": "ex-gradient-colors-radial-chart",
    "name": "Gradient Colors Radial",
    "exportName": "NQExampleGradientColorsRadialChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "radial",
    "category": "variant",
    "component": "radial-chart"
  },
  {
    "id": "ex-gradient-colors-scatter-chart",
    "name": "Gradient Colors Scatter",
    "exportName": "NQExampleGradientColorsScatterChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "scatter",
    "category": "variant",
    "component": "scatter-chart"
  },
  {
    "id": "ex-gradient-reverse-area-variant-area-chart",
    "name": "Gradient Reverse Area Variant Area",
    "exportName": "NQExampleGradientReverseAreaVariantAreaChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "area",
    "category": "variant",
    "component": "area-chart"
  },
  {
    "id": "ex-hatched-area-variant-area-chart",
    "name": "Hatched Area Variant Area",
    "exportName": "NQExampleHatchedAreaVariantAreaChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "area",
    "category": "example",
    "component": "area-chart"
  },
  {
    "id": "ex-hatched-variant-bar-chart",
    "name": "Hatched Variant Bar",
    "exportName": "NQExampleHatchedVariantBarChart",
    "adapterFile": "ex-hatched-variant-bar-chart.tsx",
    "family": "bar",
    "category": "example",
    "component": "bar-chart"
  },
  {
    "id": "ex-heatmap-chart",
    "name": "Heatmap",
    "exportName": "NQExampleHeatmapChart",
    "adapterFile": "ex-heatmap-chart.tsx",
    "family": "heatmap",
    "category": "matrix",
    "component": "heatmap-chart"
  },
  {
    "id": "ex-heatmap-correlation-chart",
    "name": "Heatmap Correlation",
    "exportName": "NQExampleHeatmapCorrelationChart",
    "adapterFile": "ex-heatmap-correlation-chart.tsx",
    "family": "heatmap",
    "category": "matrix",
    "component": "heatmap-chart"
  },
  {
    "id": "ex-heatmap-team-workload-chart",
    "name": "Heatmap Team Workload",
    "exportName": "NQExampleHeatmapTeamWorkloadChart",
    "adapterFile": "ex-heatmap-team-workload-chart.tsx",
    "family": "heatmap",
    "category": "matrix",
    "component": "heatmap-chart"
  },
  {
    "id": "ex-heatmap-weekly-chart",
    "name": "Heatmap Weekly",
    "exportName": "NQExampleHeatmapWeeklyChart",
    "adapterFile": "ex-heatmap-weekly-chart.tsx",
    "family": "heatmap",
    "category": "matrix",
    "component": "heatmap-chart"
  },
  {
    "id": "ex-histogram-chart",
    "name": "Histogram",
    "exportName": "NQExampleHistogramChart",
    "adapterFile": "ex-histogram-chart.tsx",
    "family": "bar",
    "category": "recipe",
    "component": "bar-chart"
  },
  {
    "id": "ex-horizontal-layout-bar-chart",
    "name": "Horizontal Layout Bar",
    "exportName": "NQExampleHorizontalLayoutBarChart",
    "adapterFile": "ex-horizontal-layout-bar-chart.tsx",
    "family": "bar",
    "category": "example",
    "component": "bar-chart"
  },
  {
    "id": "ex-legend-circle-line-chart",
    "name": "Legend Circle Line",
    "exportName": "NQExampleLegendCircleLineChart",
    "adapterFile": "ex-ui-charts.tsx",
    "family": "line",
    "category": "legend",
    "component": "line-chart"
  },
  {
    "id": "ex-legend-circle-outline-line-chart",
    "name": "Legend Circle Outline Line",
    "exportName": "NQExampleLegendCircleOutlineLineChart",
    "adapterFile": "ex-ui-charts.tsx",
    "family": "line",
    "category": "legend",
    "component": "line-chart"
  },
  {
    "id": "ex-legend-horizontal-bar-line-chart",
    "name": "Legend Horizontal Bar Line",
    "exportName": "NQExampleLegendHorizontalBarLineChart",
    "adapterFile": "ex-ui-charts.tsx",
    "family": "bar",
    "category": "legend",
    "component": "line-chart"
  },
  {
    "id": "ex-legend-rounded-square-line-chart",
    "name": "Legend Rounded Square Line",
    "exportName": "NQExampleLegendRoundedSquareLineChart",
    "adapterFile": "ex-ui-charts.tsx",
    "family": "line",
    "category": "legend",
    "component": "line-chart"
  },
  {
    "id": "ex-legend-rounded-square-outline-line-chart",
    "name": "Legend Rounded Square Outline Line",
    "exportName": "NQExampleLegendRoundedSquareOutlineLineChart",
    "adapterFile": "ex-ui-charts.tsx",
    "family": "line",
    "category": "legend",
    "component": "line-chart"
  },
  {
    "id": "ex-legend-square-line-chart",
    "name": "Legend Square Line",
    "exportName": "NQExampleLegendSquareLineChart",
    "adapterFile": "ex-ui-charts.tsx",
    "family": "line",
    "category": "legend",
    "component": "line-chart"
  },
  {
    "id": "ex-legend-vertical-bar-line-chart",
    "name": "Legend Vertical Bar Line",
    "exportName": "NQExampleLegendVerticalBarLineChart",
    "adapterFile": "ex-ui-charts.tsx",
    "family": "bar",
    "category": "legend",
    "component": "line-chart"
  },
  {
    "id": "ex-line-chart",
    "name": "Line",
    "exportName": "NQExampleLineChart",
    "adapterFile": "ex-line-chart.tsx",
    "family": "line",
    "category": "example",
    "component": "line-chart"
  },
  {
    "id": "ex-lines-area-variant-area-chart",
    "name": "Lines Area Variant Area",
    "exportName": "NQExampleLinesAreaVariantAreaChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "area",
    "category": "example",
    "component": "area-chart"
  },
  {
    "id": "ex-lines-variant-radar-chart",
    "name": "Lines Variant Radar",
    "exportName": "NQExampleLinesVariantRadarChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "line",
    "category": "example",
    "component": "radar-chart"
  },
  {
    "id": "ex-loading-state-area-chart",
    "name": "Loading State Area",
    "exportName": "NQExampleLoadingStateAreaChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "area",
    "category": "loading",
    "component": "area-chart"
  },
  {
    "id": "ex-loading-state-bar-chart",
    "name": "Loading State Bar",
    "exportName": "NQExampleLoadingStateBarChart",
    "adapterFile": "ex-loading-state-bar-chart.tsx",
    "family": "bar",
    "category": "loading",
    "component": "bar-chart"
  },
  {
    "id": "ex-loading-state-bubble-chart",
    "name": "Loading State Bubble",
    "exportName": "NQExampleLoadingStateBubbleChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "scatter",
    "category": "loading",
    "component": "scatter-chart"
  },
  {
    "id": "ex-loading-state-composed-chart",
    "name": "Loading State Composed",
    "exportName": "NQExampleLoadingStateComposedChart",
    "adapterFile": "ex-loading-state-composed-chart.tsx",
    "family": "composed",
    "category": "loading",
    "component": "composed-chart"
  },
  {
    "id": "ex-loading-state-funnel-chart",
    "name": "Loading State Funnel",
    "exportName": "NQExampleLoadingStateFunnelChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "funnel",
    "category": "loading",
    "component": "funnel-chart"
  },
  {
    "id": "ex-loading-state-gauge-chart",
    "name": "Loading State Gauge",
    "exportName": "NQExampleLoadingStateGaugeChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "radial",
    "category": "loading",
    "component": "radial-chart"
  },
  {
    "id": "ex-loading-state-histogram-chart",
    "name": "Loading State Histogram",
    "exportName": "NQExampleLoadingStateHistogramChart",
    "adapterFile": "ex-loading-state-histogram-chart.tsx",
    "family": "bar",
    "category": "loading",
    "component": "bar-chart"
  },
  {
    "id": "ex-loading-state-line-chart",
    "name": "Loading State Line",
    "exportName": "NQExampleLoadingStateLineChart",
    "adapterFile": "ex-loading-state-line-chart.tsx",
    "family": "line",
    "category": "loading",
    "component": "line-chart"
  },
  {
    "id": "ex-loading-state-pareto-chart",
    "name": "Loading State Pareto",
    "exportName": "NQExampleLoadingStateParetoChart",
    "adapterFile": "ex-loading-state-pareto-chart.tsx",
    "family": "composed",
    "category": "loading",
    "component": "composed-chart"
  },
  {
    "id": "ex-loading-state-radar-chart",
    "name": "Loading State Radar",
    "exportName": "NQExampleLoadingStateRadarChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "radar",
    "category": "loading",
    "component": "radar-chart"
  },
  {
    "id": "ex-loading-state-radial-chart",
    "name": "Loading State Radial",
    "exportName": "NQExampleLoadingStateRadialChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "radial",
    "category": "loading",
    "component": "radial-chart"
  },
  {
    "id": "ex-loading-state-scatter-chart",
    "name": "Loading State Scatter",
    "exportName": "NQExampleLoadingStateScatterChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "scatter",
    "category": "loading",
    "component": "scatter-chart"
  },
  {
    "id": "ex-loading-state-sparkline-chart",
    "name": "Loading State Sparkline",
    "exportName": "NQExampleLoadingStateSparklineChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "line",
    "category": "loading",
    "component": "sparkline-chart"
  },
  {
    "id": "ex-loading-state-treemap-chart",
    "name": "Loading State Treemap",
    "exportName": "NQExampleLoadingStateTreemapChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "treemap",
    "category": "loading",
    "component": "treemap-chart"
  },
  {
    "id": "ex-loading-state-waterfall-chart",
    "name": "Loading State Waterfall",
    "exportName": "NQExampleLoadingStateWaterfallChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "waterfall",
    "category": "loading",
    "component": "waterfall-chart"
  },
  {
    "id": "ex-monotoney-curve-type-area-chart",
    "name": "Monotoney Curve Type Area",
    "exportName": "NQExampleMonotoneyCurveTypeAreaChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "area",
    "category": "example",
    "component": "area-chart"
  },
  {
    "id": "ex-pareto-chart",
    "name": "Pareto",
    "exportName": "NQExampleParetoChart",
    "adapterFile": "ex-pareto-chart.tsx",
    "family": "composed",
    "category": "recipe",
    "component": "composed-chart"
  },
  {
    "id": "ex-percent-type-bar-chart",
    "name": "Percent Type Bar",
    "exportName": "NQExamplePercentTypeBarChart",
    "adapterFile": "ex-percent-type-bar-chart.tsx",
    "family": "bar",
    "category": "example",
    "component": "bar-chart"
  },
  {
    "id": "ex-pie-chart",
    "name": "Pie",
    "exportName": "NQExamplePieChart",
    "adapterFile": "ex-pie-chart.tsx",
    "family": "pie",
    "category": "example",
    "component": "pie-chart"
  },
  {
    "id": "ex-radar-chart",
    "name": "Radar",
    "exportName": "NQExampleRadarChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "radar",
    "category": "example",
    "component": "radar-chart"
  },
  {
    "id": "ex-radial-chart",
    "name": "Radial",
    "exportName": "NQExampleRadialChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "radial",
    "category": "example",
    "component": "radial-chart"
  },
  {
    "id": "ex-rose-radial-chart",
    "name": "Rose Radial",
    "exportName": "NQExampleRoseRadialChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "radial",
    "category": "example",
    "component": "radial-chart"
  },
  {
    "id": "ex-scatter-chart",
    "name": "Scatter",
    "exportName": "NQExampleScatterChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "scatter",
    "category": "example",
    "component": "scatter-chart"
  },
  {
    "id": "ex-semi-variant-radial-chart",
    "name": "Semi Variant Radial",
    "exportName": "NQExampleSemiVariantRadialChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "radial",
    "category": "example",
    "component": "radial-chart"
  },
  {
    "id": "ex-solid-area-variant-area-chart",
    "name": "Solid Area Variant Area",
    "exportName": "NQExampleSolidAreaVariantAreaChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "area",
    "category": "example",
    "component": "area-chart"
  },
  {
    "id": "ex-solid-stroke-area-chart",
    "name": "Solid Stroke Area",
    "exportName": "NQExampleSolidStrokeAreaChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "area",
    "category": "example",
    "component": "area-chart"
  },
  {
    "id": "ex-sparkline-area-chart",
    "name": "Sparkline Area",
    "exportName": "NQExampleSparklineAreaChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "area",
    "category": "example",
    "component": "sparkline-chart"
  },
  {
    "id": "ex-sparkline-chart",
    "name": "Sparkline",
    "exportName": "NQExampleSparklineChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "line",
    "category": "example",
    "component": "sparkline-chart"
  },
  {
    "id": "ex-sparkline-end-dot-chart",
    "name": "Sparkline End Dot",
    "exportName": "NQExampleSparklineEndDotChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "line",
    "category": "example",
    "component": "sparkline-chart"
  },
  {
    "id": "ex-sparkline-reference-band-chart",
    "name": "Sparkline Reference Band",
    "exportName": "NQExampleSparklineReferenceBandChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "line",
    "category": "example",
    "component": "sparkline-chart"
  },
  {
    "id": "ex-stacked-type-area-chart",
    "name": "Stacked Type Area",
    "exportName": "NQExampleStackedTypeAreaChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "area",
    "category": "example",
    "component": "area-chart"
  },
  {
    "id": "ex-stacked-type-bar-chart",
    "name": "Stacked Type Bar",
    "exportName": "NQExampleStackedTypeBarChart",
    "adapterFile": "ex-stacked-type-bar-chart.tsx",
    "family": "bar",
    "category": "example",
    "component": "bar-chart"
  },
  {
    "id": "ex-step-curve-type-area-chart",
    "name": "Step Curve Type Area",
    "exportName": "NQExampleStepCurveTypeAreaChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "area",
    "category": "example",
    "component": "area-chart"
  },
  {
    "id": "ex-stripped-variant-bar-chart",
    "name": "Stripped Variant Bar",
    "exportName": "NQExampleStrippedVariantBarChart",
    "adapterFile": "ex-stripped-variant-bar-chart.tsx",
    "family": "bar",
    "category": "example",
    "component": "bar-chart"
  },
  {
    "id": "ex-treemap-chart",
    "name": "Treemap",
    "exportName": "NQExampleTreemapChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "treemap",
    "category": "example",
    "component": "treemap-chart"
  },
  {
    "id": "ex-waterfall-chart",
    "name": "Waterfall",
    "exportName": "NQExampleWaterfallChart",
    "adapterFile": "ex-doc-charts.tsx",
    "family": "waterfall",
    "category": "example",
    "component": "waterfall-chart"
  },
  {
    "id": "ex-workload-dashboard-chart",
    "name": "Workload Dashboard",
    "exportName": "NQExampleWorkloadDashboardChart",
    "adapterFile": "ex-workload-dashboard-chart.tsx",
    "family": "calendar",
    "category": "matrix",
    "component": "calendar-chart"
  },
  {
    "id": "grid-bar-chart",
    "name": "Grid Bar",
    "exportName": "NQGridBarChart",
    "adapterFile": "b-grid-bar-chart.tsx",
    "family": "bar",
    "category": "block",
    "component": "bar-chart"
  },
  {
    "id": "hover-trace-bar-chart",
    "name": "Hover Trace Bar",
    "exportName": "NQHoverTraceBarChart",
    "adapterFile": "b-hover-trace-bar-chart.tsx",
    "family": "bar",
    "category": "variant",
    "component": "bar-chart"
  },
  {
    "id": "isometric-bar-chart",
    "name": "Isometric Bar",
    "exportName": "NQIsometricBarChart",
    "adapterFile": "b-isometric-bar-chart.tsx",
    "family": "bar",
    "category": "block",
    "component": "bar-chart"
  },
  {
    "id": "monospace-bar-chart",
    "name": "Monospace Bar",
    "exportName": "NQMonospaceBarChart",
    "adapterFile": "b-monospace-bar-chart.tsx",
    "family": "bar",
    "category": "variant",
    "component": "bar-chart"
  }
];

export const NQCHART_FAMILIES = [...new Set(NQCHART_CATALOG.map((e) => e.family))].sort();

